### ISSUE TITLE
Show entries regardless of geolocation permission

### ISSUE THREAD

**Issue by johnjohndoe** [codeforberlin/sprachcafes#1]
When I open the [website](http://www.refugeeacademy.de/karte-sprachcafes/) the following popup is shown "Geolocation error: User denied geolocation prompt.":

![error](https://user-images.githubusercontent.com/144518/30736202-1a1e85be-9f82-11e7-8c5d-30433e8e6553.png)

When I confirm the popup **no entry** is shown.

**Comment by jochenklar** [comment]
fixed with new version of sprachcafes.txt and automatic redirect to HTTPS.
